build:
  maxIssues: 10
  excludeCorrectable: true
  weights:
    complexity: 1
    style: 1
    comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

processors:
  active: true
  exclude:
    - 'DetektProgressListener'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'

output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'

comments:
  active: true
  AbsentOrWrongFileLicense:
    active: false
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false

complexity:
  active: true
  CognitiveComplexMethod:
    active: false
  ComplexCondition:
    active: true
    threshold: 4
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 12
    constructorThreshold: 10

coroutines:
  active: true
  InjectDispatcher:
    active: true
    dispatcherNames:
      - 'IO'
      - 'Default'
  RedundantSuspendModifier:
    active: true

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
  EmptyClassBlock:
    active: true

exceptions:
  active: true
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: true

performance:
  active: true
  ArrayPrimitive:
    active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: true

potential-bugs:
  active: true
  AvoidReferentialEquality:
    active: true
    forbiddenTypePatterns:
      - 'kotlin.String'
  IgnoredReturnValue:
    active: true

naming:
  active: true
  VariableMaxLength:
    active: true
    maximumVariableNameLength: 30
  FunctionMaxLength:
    active: true
    maximumFunctionNameLength: 50

style:
  UnusedImports:
    active: true
